.eslintrc.cjs, src/App.tsx, src/main.tsx
eslint에서 tsconfig.json에 포함되지 않은 파일들에 대해 오류가 발생 중이였습니다. 
이것을 해결하기 위해 .eslintrc.cjs 파일을 수정했습니다
```ts
// .eslintrc.cjs
rules: {
'import/no-extraneous-dependencies': "off", // 이 줄 추가
'react-refresh/only-export-components': [
'warn',
{ allowConstantExport: true },
],
},
parserOptions: {
tsconfigRootDir: './',
project: ['./tsconfig.json', './tsconfig.app.json', './tsconfig.node.json']
},
```
<br><br>
=> [FE] chore: eslint-airbnb 초기 세팅

.eslintrc.cjs, src/main.tsx, src/ui/Header.tsx, src/ui/Layout.tsx
=> eslint 설정 변경

.gitignore, src/components/Header.tsx, src/components/common/Button.tsx, src/components/mypage/AllOrderTab.tsx, src/components/mypage/MyPageOrder.tsx, src/components/mypage/MyPageOrderList.tsx, src/components/mypage/MyPageProfile.tsx, src/components/order/OrderListTab.tsx, src/components/order/OrderProduct.tsx, src/components/product/ProductListTabs.tsx, src/components/profile/ProfileInput.tsx, src/components/profile/SelectCountry.tsx, src/constants/route.ts, src/pages/AllOrderList.tsx, src/pages/Login.tsx, src/pages/MyPage.tsx, src/pages/OrderHistoryPage.tsx, src/pages/ProfileEditPage.tsx, src/pages/Signup.tsx, src/routing.tsx
```tsx
const MyPage = () => {
return (
<Layout header={<Header path="/">마이페이지</Header>} footer={myPageFooter}>
<div className="flex flex-col">
<MyPageProfile />
<MyPageOrder />
<MyPageOrderList />
</div>
</Layout>
);
};
```
```tsx
// MyPageProfile
const MyPageProfile = () => {
return (
<div className="flex items-center pb-8 mb-10 border-b border-b-gray3">
<div className="w-20 h-20 rounded-full bg-gray-300 mr-4" />
<div className="flex-1">
<div className="flex items-center justify-between">
<div className="flex items-center">
<p className="text-lg font-bold mr-2 pr-2 border-r border-r-gray3">
{mockData.nickname}
</p>
<p>{mockData.country}</p>
</div>
<button className="px-3 py-1 border border-gray2 rounded-md">
수정
</button>
</div>
<div className="mt-2">
<div className="font-bold">자기소개</div> …
```
=> Feat: 주문 내역페이지, 마이페이지, 회원가입 페이지 마크업

src/components/Layout.tsx
=> style: Layout 구조를 compound pattern으로 변경

src/@types/Product.d.ts, src/components/bid/BidCaution.tsx, src/components/bid/queries.ts, src/constants/caution.ts, src/hooks/useEditableNumberInput.ts, src/mocks/broswer.ts, src/mocks/data/bidProductData.ts, src/mocks/handlers/details.ts, src/pages/Bid.tsx, src/routing.tsx, src/tests/EditBid.test.tsx, src/utils/formatCurrencyWithWon.ts
=> test & feat: 입찰 수정

.eslintrc.cjs, src/api/axios.ts, src/components/common/ProductItem.tsx, src/components/home/CategoryList.tsx, src/components/home/queries.ts, src/components/login/queries.ts, src/components/productList/queries.ts, src/hooks/useAuth.ts, src/hooks/useProductList.ts, src/pages/Home.tsx, src/pages/Login.tsx, src/pages/ProductList.tsx, src/store/authSlice.ts
=> Fix: 로그인 navigate 수정, category URL 수정

src/components/bid/queries.ts, src/components/home/CategoryList.tsx, src/components/productList/OngoingProduct.tsx, src/constants/api.ts, src/pages/Bid.tsx, src/router.tsx
=> Test / bid flow

src/App.tsx, src/api/axios.ts, src/components/login/queries.ts, src/hooks/useSignup.ts, src/pages/Signup.tsx
```js
import axios, { AxiosError, AxiosRequestConfig } from 'axios';
import { getToken, removeToken, setToken } from '@/utils/tokenUtils';
import { refreshToken } from '@/components/login/queries';
import { toast } from 'sonner';
interface AxiosRequestConfigWithRetry extends AxiosRequestConfig {
_retry?: boolean;
}
interface ErrorResponseData {
message: string;
status: string;
name: string;
}
const handleTokenError = (message: string) => {
removeToken();
toast(message);
window.location.href = '/login';
};
export const createClient = (config?: AxiosRequestConfig) => {
const axiosInstance = axios.create({
baseURL: import.meta.env.VITE_API_URL,
headers: {
'Content-Type': 'application/json',
},
withCredentials: true,
timeout: 5000,
...config,
});
axiosInstance.interceptors.request.use(async …
```
=> Fix: 로그인 토큰 재정립

src/router.tsx
=> fix: bidder list asyncboundary 적용

src/@types/bid.d.ts, src/components/bid/queries.ts, src/components/bidderList/queries.ts, src/components/common/item/ProductItem.tsx, src/components/details/BuyersFooter.tsx, src/components/details/queries.ts, src/components/register/RegisterCaution.tsx, src/pages/AuctionDetails.tsx, src/pages/Bid.tsx, src/pages/BidderList.tsx, src/pages/PreAuctionDetails.tsx, src/router.tsx
=> feat: Carousel 추가 및 적용, 경매 등록 수정

src/@types/AuctionItem.d.ts, src/components/common/CustomCarousel.tsx
=> 타입 변수명 변경 및 Carousel loop 추가

src/@types/AuctionItem.d.ts, src/components/bid/Bid.test.tsx, src/components/bid/EditBid.test.tsx, src/components/common/CustomCarousel.tsx, src/components/common/item/ProductItem.tsx, src/components/details/BuyersFooter.tsx, src/components/details/queries.ts, src/components/home/CategoryList.tsx, src/components/register/RegisterCaution.tsx, src/constants/categories.ts, src/mocks/data/auctionDetailsData.ts, src/pages/AuctionDetails.tsx, src/pages/PreAuctionDetails.tsx, src/pages/Register.tsx, src/router.tsx
=> dev to main

src/components/common/item/ProductItem.tsx, src/components/login/queries.ts, src/components/order/OrderListTab.tsx, src/components/order/OrderLostProduct.tsx, src/components/order/OrderWonProduct.tsx, src/components/user/UserOrder.tsx, src/components/user/UserProfile.tsx, src/components/user/queries.ts, src/hooks/useMyAuctionList.ts, src/hooks/useProfile.ts, src/pages/User.tsx
=> feat: 내가 등록한 경매 URL 수정

src/pages/Register.tsx
현재 카테고리 값은 useForm의 control에서 관리되기 때문에 useForm의 setValue 함수로 기본값을 설정해야 한다.
또한 사전 경매 데이터를 비동기로 불러오는 것이기 때문에 값이 도착한 후에 form의 기본값으로 설정해야 한다.
이를 위해 useEffect를 사용하여 setValue 함수로 기본값을 설정한다.
closes #109
=> fix: 사전 경매 수정시 카테고리 값 불러오기

src/constants/schema.ts, src/hooks/useEditableNumberInput.ts, src/pages/Bid.tsx
=> fix: 시작가부터 입찰 가능

src/components/bidderList/queries.ts, src/pages/BidderList.tsx
=> Feat: bidder list sort 및 접근 제한

src/components/common/Button.tsx, src/components/common/loading/ButtonSpinner.tsx, src/components/home/CategoryList.tsx
=> style: 버튼 및 카테고리 스타일 변경

src/components/order/OrderWonProduct.tsx, src/constants/notification.ts
=> Fix: isOrdered ture, false 수정 및 notification에서 payment -> shipping으로 수정

src/components/common/item/AuctionItem.tsx, src/components/common/item/ProductItem.tsx, src/components/order/OrderWonProduct.tsx, src/components/user/EndMyRegister.tsx, src/components/user/PreEnrollMyRegister.tsx, src/constants/address.ts, src/pages/AuctionShipping.tsx, src/pages/DeliveryAddressAdd.tsx, src/pages/DeliveryAddressEdit.tsx, src/pages/DeliveryAddressList.tsx
=> Fix: 테스트 보완사항

src/@types/user.ts, src/components/login/queries.ts, src/components/profile/queries.ts, src/components/user/UserOrder.tsx, src/components/user/UserProfile.tsx, src/constants/schema.ts, src/hooks/useProfile.ts, src/hooks/useSignup.ts, src/pages/Login.tsx, src/pages/ProfileEdit.tsx, src/pages/Signup.tsx, src/pages/User.tsx, tailwind.config.js
=> fix: 로그인 페이지 스타일 수정, 회원가입, 프로필 수정 페이지 스타일 수정 및 useHooks 분리

src/components/bid/BidMain.tsx, src/components/details/AuctionDetailsFooter.tsx, src/components/details/PreAuctionDetailsFooter.tsx, src/components/details/ProgressBar.tsx, src/components/details/queries.ts, src/components/heart/queries.ts, src/components/notification/queries.ts, src/components/productList/PreAuctionProduct.tsx, src/components/productList/queries.ts, src/components/user/UserProfile.tsx, src/constants/schema.ts, src/hooks/useEditableNumberInput.ts, src/hooks/useEndAuction.ts, src/pages/AuctionDetails.tsx, src/pages/Heart.tsx, src/pages/Register.tsx
200만원으로 제한.
자기 소개 및 상품 설명 줄바꿈 가능하게 수정.
경매 등록은 개행문자 10개 이하로 제한.
```jsx
.superRefine((value, ctx) => {
const name = value.replaceAll(' ', '');
const newLineCount = (value.match(/\n/g) || []).length;
if (name.length === 0 || name.length < 5) {
ctx.addIssue({
code: z.ZodIssueCode.custom,
message: '상품 설명은 공백을 제외하고 5자 이상 입력해 주세요.',
});
}
if (name.length > 1000) {
ctx.addIssue({
code: z.ZodIssueCode.custom,
message: '상품 설명은 최대 1000자 이하로 입력해 주세요.',
});
}
if (newLineCount > 10) {
ctx.addIssue({
code: z.ZodIssueCode.custom,
message: '상품 설명은 줄바꿈을 10개 이하로 입력해 주세요.',
});
}
})
```
productlist에서 사용할 query 따로 작성.
```tsx
export const useToggleAuctionListHeart = (): {
mutate: UseMutateFunction<any, Error, number, unknown>;
} => {
const heartAuctionItem = async (preAuctionId: number): Promise<{ isLiked: …
```
=> Feat: 3차 회의 기능 보완

src/components/common/CustomCarousel.tsx, src/components/details/DetailsBasic.tsx, src/components/details/ProgressBar.tsx, src/components/home/CategoryList.tsx, src/components/home/HomeItem.tsx, src/pages/AuctionDetails.tsx, src/pages/PreAuctionDetails.tsx
=> Fix: 디자인 수정

src/components/address/queries.ts, src/components/user/UserOrder.tsx, src/components/user/UserProfile.tsx, src/pages/payment/ui/Payment.tsx, src/pages/payment/ui/PaymentAddressAdd.tsx, src/pages/payment/ui/PaymentAddressEdit.tsx, src/pages/payment/ui/PaymentAddressEditList.tsx, src/pages/payment/ui/PaymentAddressList.tsx, src/pages/sign-up/ui/Signup.tsx, src/pages/user/ui/UserProfileEdit.tsx
=> Fix: 750px 화면 스타일 수정

src/components/address/Address.test.tsx
=> fix: address 테스트 코드 수정

src/app/layout/ui/GlobalLayout.tsx, src/app/layout/ui/Layout.tsx, src/app/main.tsx, src/features/details/model/useToggleAuctionDetailsHeart.ts, src/features/heart/model/useDeletePreAuctionHeart.ts, src/features/product-list/model/useToggleAuctionListHeart.ts, src/shared/ui/AuctionItem.tsx, src/shared/ui/Modal.tsx, tailwind.config.js
찜하기를 성공하고 찜하기 삭제를 성공할 때 메시지를 보여주는 것은 필요없다고 생각이 들었습니다.
대신 찜하기, 찜하기 삭제를 실패했을 때 에러 메시지를 보여주는 것으로 대체했습니다.
closes #210
=> Fix: 기능 개선

src/shared/ui/Confirm.tsx, src/shared/ui/Modal.tsx
=> style: modal 수정

src/shared/ui/AuctionForm.tsx
=> Fix : form defaultValues 설정

.github/workflows/deploy.yml
github secrets에 .env.production 파일 추가해서 사용했습니다.
closes #이슈번호
=> fix: .env.production 추가

src/entities/auction/model/types/userParticipated.ts, src/features/address/api/getAddressDetail.ts, src/features/address/model/usePostPayment.ts, src/features/product-list/api/getEnrollProductList.ts, src/features/user/api/getMyLostAuction.ts, src/features/user/api/getMyWonAuction.ts, src/pages/payment/ui/Payment.tsx, src/pages/user/ui/UserParticipatedList.tsx, src/shared/constants/apiEndPoint.ts
=> Refactoring: 수정된 auction api에 맞춰 코드 수정

src/features/product-list/model/useProductList.ts, src/features/user/api/deleteUsers.ts, src/features/user/model/useDeleteUsers.ts, src/features/user/model/useHistory.ts, src/features/user/model/useMyAuctionList.ts, src/features/user/ui/UserOrderList.tsx, src/pages/product-list/ui/ProductList.tsx, src/pages/user/ui/UserParticipatedList.tsx, src/pages/user/ui/UserPreRegisteredList.tsx, src/pages/user/ui/UserRegisteredList.tsx, src/shared/constants/confirmMessage.ts
=> Feat: 회원 탈퇴 기능추가

src/app/layout/ui/Layout.tsx, src/app/layout/ui/LayoutWithNav.tsx, src/app/router.tsx, src/pages/home/ui/Home.tsx, src/pages/home/ui/HomeSearchBar.tsx, src/pages/search/ui/AuctionSearch.tsx, src/shared/ui/Command.tsx
- 홈 화면에서 검색 스타일 수정이 필요합니다.
- 검색 화면에서 다시 검색할 때 검색어 반영이 안되는 듯 합니다.
closes #이슈번호
=> style: 검색 스타일 수정

index.html
=> Fix: preconnect 수정

index.html
=> fix: preconnect

src/features/bid/ui/BidForm.tsx, src/features/details/ui/AuctionDetailsMain.tsx, src/features/details/ui/PreAuctionDetailsMain.tsx, src/pages/bid/ui/Bid.tsx, src/pages/details/ui/AuctionDetails.tsx, src/pages/details/ui/PreAuctionDetails.tsx, src/pages/settlement/ui/Settlement.tsx, src/pages/settlement/ui/SettlementMain.tsx
=> style: boundary 스타일 수정

package-lock.json, package.json, src/features/address/test/Address.test.tsx, src/features/auction-search/api/index.ts, src/features/auction-search/test/AuctionSearch.test.tsx, src/features/auth/test/Login.test.tsx, src/features/product-list/test/ProductList.test.tsx, src/features/profile/test/ProfileEdit.test.tsx, src/features/sign-up/hooks/useSignupNicknameValidate.ts, src/features/sign-up/test/Signup.test.tsx, src/features/user/test/User.test.tsx, src/features/user/test/UserParticipatedList.test.tsx, src/features/user/test/UserRegisteredList.test.tsx, src/features/user/ui/UserProfile.tsx, src/shared/utils/formatCurrencyWithWon.ts
=> Feat: 테스트 코드 수정 및 추가

src/features/product-list/test/ProductList.test.tsx, src/features/profile/test/ProfileEdit.test.tsx, src/features/sign-up/test/Signup.test.tsx, src/features/user/test/User.test.tsx, src/features/user/test/UserParticipatedList.test.tsx, src/features/user/test/UserRegisteredList.test.tsx
=> fix: 테스트 에러 수정

src/features/details/test/data.ts, src/features/heart/test/data.ts, src/features/notification/test/data.ts, src/pages/home/test/data.ts
=> fix: 테스트 용 이미지 경로 수정

vite.config.ts
=> fix: 테스트 이미지 빌드 설정 수정

src/features/auth/hooks/useAuth.ts, src/features/auth/test/handler.ts, src/features/product-list/test/handler.ts, src/features/user/test/handler.ts, src/shared/api/msw/browser.ts
=> Refactoring: 로그인 모킹 코드 수정

cypress/e2e/Bid.cy.ts, cypress/e2e/EndAuction.cy.ts
=> fix: e2e-test 수정

.github/workflows/integration-main.yml, src/app/main.tsx
=> fix: ci-workflow

.github/workflows/integration-main.yml
=> feat: ci workflow 최적화

.github/workflows/integration-main.yml
=> fix: CI workflow 수정

src/features/details/ui/AuctionDetailsMain.tsx, src/features/details/ui/PreAuctionDetailsMain.tsx, src/features/notification/ui/NotificationItem.tsx, src/features/user/ui/OrderWonProduct.tsx, src/pages/payment/ui/Payment.tsx, src/shared/ui/AuctionItem.tsx, src/shared/ui/ProductItem.tsx, src/shared/ui/ProgressiveImage.tsx, src/shared/ui/index.ts, src/stories/components/product/ProductItem.test.tsx
저해상도 이미지 빠르게 불러오고 그 뒤에 로드되는 고해상도 이미지 덮어씌움으로써 사용자 경험 향상
closes #이슈번호
=> refactor: 이미지 최적화

package-lock.json, package.json, src/app/main.tsx, src/pages/home/lib/useScrollDetection.ts, src/pages/home/ui/Home.tsx, src/pages/home/ui/HomeRegisterBtn.tsx
react-scan 라이브러리 통해 발견했습니다.
사용해보시고 각자 파트에서 수정할 부분 찾아 최적화하면 좋을 듯 합니다.
https://github.com/aidenybai/react-scan
closes #이슈번호
=> refactor: rendering optimization

.github/workflows/integration-main.yml
=> fix: workflow 수정

.github/workflows/integration-main.yml
=> fix: workflow container 수 조정

package-lock.json, package.json, src/app/router.tsx, src/features/auth/api/postSignup.ts, src/features/auth/hooks/useAuth.ts, src/features/auth/index.ts, src/features/auth/model/useRefreshTokenOnSuccess.ts, src/features/auth/test/handler.ts, src/pages/bid/index.ts, src/pages/bid/ui/Bid.tsx, src/pages/bid/ui/index.ts, src/pages/bidder-list/index.ts, src/pages/bidder-list/ui/BidderList.tsx, src/pages/bidder-list/ui/index.ts, src/pages/details/index.ts, src/pages/details/ui/AuctionDetails.tsx, src/pages/details/ui/PreAuctionDetails.tsx, src/pages/details/ui/index.ts, src/pages/edit-auction/index.ts, src/pages/edit-auction/ui/EditAuction.tsx, src/pages/edit-auction/ui/index.ts, src/pages/home/ui/BestItemList.tsx, src/pages/home/ui/ImminentItemList.tsx, src/pages/home/ui/PreAuctionItemList.tsx, src/shared/api/axios.ts, src/shared/utils/RouteLoader.ts, src/shared/utils/index.ts, vite.config.ts
- rollup-plugin-visualizer 라이브러리 활용하여 현재 bundle에서 각 차지하고 있는 부분 시각적으로 확인했습니다.
- 변동사항이 거의 없는 부분은 다른 chunck로 분리함으로써 업데이트되지 않는 한 브라우저 캐시로 활용할 수 있게끔 했습니다
- 용량 많이 차지하는 라이브러리의 의존성 확인해서 초기 로딩에 필요없는 라이브러리 또한 다른 chunck로 분리함으로써 초기 로딩 속도 개선했습니다.
closes #이슈번호
=> refactor: code splitting

vite.config.ts
react 내부 훅을 사용하는 dnd-kit를 react와 다른 chunk로 묶어 에러 발생
그래서 같은 chunk로 설정.
closes #이슈번호
=> fix: bundle option 수정

vite.config.ts
배포에서 bundle 가지고 오지 못하는 에러 수정.
closes #이슈번호
=> fix: bundle chunk 수정

package-lock.json, vite.config.ts
=> refactor: bundle option

src/app/router.tsx
=> refactoring: 병합 오류 해결

src/entities/address/address.ts, src/features/address/config/index.ts, src/features/address/config/schema.ts, src/features/auth/hooks/useAuth.ts, src/features/sign-up/test/Signup.test.tsx, src/pages/payment/ui/Payment.tsx, src/pages/payment/ui/PaymentAddressAdd.tsx, src/pages/payment/ui/PaymentAddressEdit.tsx, src/pages/sign-up/ui/Signup.tsx, src/shared/ui/FormField.tsx
```tsx
The file does not exist at "/Users/apple/Documents/GitHub/aquaman122.github.io/Chzz-Market-Frontend/node_modules/.vite/deps/sw.js" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
```
참고: (https://github.com/vitejs/vite/discussions/17738)
closes #293
=> refactoring: 렌더링 최적화 및 로그인 코드 수정 

src/features/auth/hooks/useAuth.ts, src/shared/ui/AuctionForm.tsx, src/shared/ui/Button.tsx, src/stories/components/product/ProductItem.mdx
로그인 mocking 코드가 development 환경에서만 동작하도록 추가 설정
closes #이슈번호
=> fix: login cors

src/features/auth/hooks/useAuth.ts
=> fix: mode 수정

src/features/product-list/ui/PreAuctionProduct.tsx
=> Bugfix: 사전 경매 버튼 오류수정

src/features/auth/model/useRefreshTokenOnSuccess.ts, src/features/auth/test/Login.test.tsx, src/pages/home/test/Home.test.tsx, src/pages/home/ui/Home.tsx, src/pages/login/Login.tsx
=> refactoring: 로그인 성공 시 경로 수정

.github/workflows/integration-main.yml
=> fix: matrix 삭제

.github/workflows/deploy.yml
=> fix: 오타 수정

index.html
=> feat: preconnect

README.md, src/shared/api/axios.ts, src/shared/constants/apiEndPoint.ts
=> Bugfix: axios apis 이전 코드로 수정 및 리드미 파일 수정

src/pages/payment/ui/Payment.tsx, src/pages/payment/ui/PaymentAddressEditList.tsx, src/pages/payment/ui/PaymentAddressList.tsx
=> fix: icon-style

README.md, src/features/user/ui/EndMyRegister.tsx, src/features/user/ui/OrderWonProduct.tsx, src/pages/payment/ui/Payment.tsx, src/pages/payment/ui/PaymentAddressEditList.tsx, src/pages/payment/ui/PaymentAddressList.tsx, src/shared/constants/apiEndPoint.ts, src/shared/ui/CreatedAt.tsx
=> refactoring: icon 사이즈 변경

src/shared/api/axios.ts
=> refactoring: axios 로그인 필요 코드 수정

src/shared/api/axios.ts
=> Refactoring: 토큰 만료시 페이지 강제이동 삭제
