src/assets/icons/participants.svg, src/components/details/BuyersFooter.tsx, src/components/details/ProgressBar.tsx, src/components/details/SellersFooter.tsx, src/constants/api.ts, src/constants/route.ts, src/hooks/useFormatTime.ts, src/hooks/useProgress.ts, src/mocks/broswer.ts, src/mocks/data/auctionDetailPageData.ts, src/mocks/handlers/auctionDetailPage.ts, src/pages/DetailPage.tsx, src/routing.tsx
1. api 명세에 맞게 더미 데이터를 만들고 fecthing할 수 있도록 하였습니다
2. 그리고 해당 데이터를 받아서 실제 서비스처럼 랜더링 되도록 하드코딩 된 부분을 수정했습니다
3. 판매자/구매자에 따라서 보여지는 footer 버튼이 달라지도록 수정했습니다.
4. 판매자일 경우 사전경매 등록 상태 / 실 경매상태에 따라서 '경매로 전환하기' / '내가 올린 경매입니다' 문구와 버튼이 노출되도록
수정했습니다
5. 구매자일 경우 경매 물픔의 상태(사전경매 or 실경매) 및 구매자가 경매에 참여할 경우, 가격 제시 횟수가 소진되었을 경우, 경매가 종료되었을 경우에 따라서 footer 형태가 바뀌도록 수정했습니다.
closes #이슈번호
=> refactor: api 명세에 맞게 데이터 fetching 수정

src/hooks/useSignup.ts, src/pages/Login.tsx, src/pages/Signup.tsx, src/pages/User.tsx
=> Fix: 로그인 버튼 스타일 수정

src/components/bid/BidFooter.tsx, src/constants/bid.ts, src/constants/schema.ts, src/hooks/useEditableNumberInput.ts, src/pages/Bid.tsx, src/pages/BidderList.tsx
입찰 기능이 잘 작동하는지 테스트한다.
closes #75
=> Test / bid flow

src/hooks/useSSE.ts
SSE 에러가 발생하는 경우는 두 가지 경우이다.
첫 번째는 EventSourcePolyfill을 사용해서 default 45초 동안, 또는 서버와 합의해서 설정한 heartbeat(30분) 시간 동안 아무 요청이 없으면 연결을 끊어서 에러가 발생한다.
onerror 이벤트에서 연결을 close하고 3초뒤에 다시 재연결함으로써 error를 handling 한다.
두 번째는 이번에 해결하려는 재연결을 하는 과정에서 토큰이 만료되는 문제이다.
onerror 이벤트에서 재연결을 할 때 access token이 만료되거나 없으면 refreshToken function을 사용해서 쿠키에 담겨 있는 refresh token을 기반으로 access token을 재발급한다.
하지만 refresh token이 만료된 상황이라면 refreshToken function에서 error를 throw한다.
onerror 이벤트에서는 try...catch로 error를 캐치하여 사용자를 로그아웃 시키고 로그인페이지로 redirect시키고 재로그인을 유도한다.
closes #95
=> fix: sse refresh token 만료시 발생하는 error handling

package-lock.json, package.json, src/components/common/CustomCarousel.tsx, src/components/home/HomeAuctionItem.tsx, src/components/home/HomeItemList.tsx, src/components/register/ImageUploader.tsx, src/components/register/RegisterCaution.tsx, src/components/register/quries.ts, src/components/ui/button.tsx, src/components/ui/carousel.tsx, src/constants/caution.ts, src/pages/Home.tsx
홈페이지, 경매 등록 페이지에서 여러 이미지를 잘 보기 위해 캐러셀을 적용한다.
closes #96
=> Feature: 홈페이지, 경매 등록 이미지 캐러셀 적용

src/components/details/BuyersFooter.tsx, src/components/details/SellersFooter.tsx, src/pages/AuctionDetails.tsx, src/pages/PreAuctionDetails.tsx
- [] 판매자일 경우 경매로 전환하기 버튼을 누르면 실제 경매로 해당 아이템이 전환되도록 구현
- [] 판매자일 경우 수정하기 버튼을 누를 경우 아이템 수정이 가능하도록 구현
- [] 구매자일 경우 좋아요 버튼을 누를 수 있도록 구현 
closes #이슈번호
=> Feat: 사전경매 페이지 footer 구현

src/@types/AuctionDetails.d.ts, src/@types/Register.d.ts, src/components/details/queries.ts, src/components/home/HomeAuctionItem.tsx, src/components/register/quries.ts, src/constants/route.ts, src/pages/PreAuctionDetails.tsx, src/pages/Register.tsx
=> feat: 사전 등록 수정 기능

src/components/details/BuyersFooter.tsx, src/components/details/SellersFooter.tsx, src/components/details/queries.ts, src/pages/PreAuctionDetails.tsx
=> Feat: pre-auction footer 좋아요 기능 추가

src/hooks/useSSE.ts
SSE 연결 종료 후 새로운 access token을 발급받지만, 재연결 요청에는 새로 생성된 토큰이 반영되지 않아 만료된 토큰으로 인해 401 에러 발생.
closes #113
=> Bug: SSE 401 에러

src/components/common/atomic/TimeLabel.tsx, src/components/register/ImageUploader.tsx, src/components/register/quries.ts, src/pages/Register.tsx
=> Feat: register post 및 patch loading

src/components/navigation/Navigation.tsx, src/components/notification/queries.ts
- useGetNotifications Hook내에서 로그인 여부를 판단하여 로그인되어있지 않으면 API 요청하지 않고 빈 배열 리턴한다.
closes #73
=> fix: footer notification query를 login 상황에서만 실행

src/@types/AuctionDetails.d.ts, src/@types/Register.d.ts, src/components/register/ImageUploader.tsx, src/hooks/useImageUploader.ts, src/pages/PreAuctionDetails.tsx, src/pages/Register.tsx, src/utils/dataURLToFile.ts
기존 이미지(DB에 저장된 이미지의 id와 URL)를 existingImages에 따로 저장해두고,
사용자의 preview로 사용할 이미지의 초기값으로 저장한다.
사용자는 preview에 저장된 이미지의 순서를 변경하고 삭제하고 새로운 이미지를 저장하여 변하는 값이지만,  existingImages는 변하지 않는다.
최종 수정할 때 preview에는 두 가지 타입의 이미지가 있다.
하나는 data:로 시작하는 이미지로, 사용자가 file input으로 새로 삽입한 이미지이며 미리보기를 위해 dataURL로 변환한 값이다.
나머지는 DB에서 받아온 기존이미지의 URL이다.
data:로 시작하는 새로 받은 이미지만 따로 뽑아서 dataURLtoFile 함수를 통해 다시 File 타입으로 변환하고, 이 새로 삽입한 이미지가 preview에서 몇 번째에 위치하는지 기록한다. 전송할 때, formData의 key 값에는 preview의 index를 넣고 value에 file 타입 데이터를 전송한다.
기존 이미지가 현재 어느 위치에 있는지 계산하여 imageSequence 변수에 저장한다.
existingImages를 조회해서 기존 이미지가 preview에서 어느 위치에 있는지 확인하고, Map 자료구조의 key값으로는 이미지의 id값, value값으로는 이 이미지의 preview index값을 기록한다.
삭제된 이미지는 기록하지 않고 현재 존재하는 이미지가 어느 index에 있는지만 기록한다.
closes #119
=> Fix: 사전등록 수정시 이미지 처리 버그

package-lock.json, package.json, src/@types/AuctionDetails.d.ts, src/components/details/BuyersFooter.tsx, src/components/details/SellersFooter.tsx, src/components/details/queries.ts, src/components/layout/Layout.tsx, src/components/payment/PaymentForm.tsx, src/constants/route.ts, src/pages/AuctionDetails.tsx, src/pages/Payment.tsx, src/pages/PreAuctionDetails.tsx, src/router.tsx
**공통부분**
-[x]좌측에 하트, 좋아요를 누른 사람의 수, 우측에 primary 컬러의 버튼이 위치해야함
**판매자**
-[x]좌측의 하트 버튼은 클릭할 수 없음
-[x] 좌측의 하트 버튼 옆에 좋아요를 누른 사람의 수가 보여져야함
-[x]우측의 primary 컬러의 버튼은 '경매로 전환하기' 버튼이어야함
-[x]우측의 primary 컬러의 버튼을 누르면 '경매로 전환하시겠습니까?' 라는 dialog가 실행되어야함
-[x]경매로 전환을 확정하면 경매 등록 페이지로 넘어가야함
**구매자**
-[x]좌측의 하트 버튼은 클릭할 수 있고 클릭 시 하트의 색이 칠해져야함
-[x]좌측의 하트 버튼 옆에 좋아요를 누른 사람의 수가 보여져야함
-[x]우측의 primary 컬러의 버튼은 '오픈 알림 받기' 버튼이어야함
-[x]우측의 primary 컬러의 버튼을 누르면 '해당 아이템의 경매 등록 소식을 받으시겠습니까?' 라는 dialog가 실행되어야함
-[x]등록 소식을 받겠다는 버튼을 누르면 알림에 등록되어야함
closes #88
=> Feat: 경매 상세/사전 경매 상세 페이지 구현 완료

src/components/details/ImageItem.tsx, src/components/details/ImageList.tsx, src/components/details/queries.ts, src/hooks/useImageUrls.ts, src/pages/AuctionDetails.tsx, src/pages/PreAuctionDetails.tsx
[Carousel 구현]
1. AuctionDetails / PreAuctionsDetails에서 imageUrls을 받아 Carousel 구현
2. 경매 상세정보 / 사전 경매 상세정보에서 imageUrls이 전달되는 형식이 달라 이를 parsing하기 위해 useImageUrls hook 생성
3. useImageUrls 훅에서 props로 입력받은 데이터를 검사하여 데이터가 string으로 구성되어 있을 경우 key / imageUrl 그대로 전달
4. Object일 경우 Objectd에서 imageId와 ImageUrl을 추출하여 return
5. Object일 경우이면서 key값이 존재하지 않을 경우를 대비하여 key값에 idx+1이 할당되도록 수정
6. useImageUrls hook을 통해 parsing된 데이터를 ImageItem에 전달하여 Carousel 아이템 생성
7. ImageItem을 ImageList에 children으로 전달하여 Carousel 구현
[queries]
1. useConvertToAuction 쿼리에서 onSuccess시 아래 4개의 query를 무효화 하도록 수정
2. 좋아요 클릭시 useLikeAuctionItem 에서 PRE_AUCTION_HEART_LIST, PRE_AUCTION_DETAILS 를 무효화 하도록 수정
4. LIST를 LOST로 작성한 오타 수정
1. queries 부분에서 불필요한 부분이 있다고 생각되면 수정 요망
closes #이슈번호
=> Feat: 케로셀 구현 외

src/api/axios.ts, src/components/common/CustomCarousel.tsx, src/components/common/boundary/APIAsyncBoundary.tsx, src/components/common/boundary/LocalAPIAsyncBoundary.tsx, src/components/common/loading/LocalSpinner.tsx, src/components/details/queries.ts, src/components/home/CategoryList.tsx, src/components/login/queries.ts, src/components/navigation/Navigation.tsx, src/components/notification/queries.ts, src/pages/Notification.tsx, src/pages/PreAuctionDetails.tsx, src/pages/Test.tsx, src/router.tsx, tsconfig.app.json
=> Fix: rendering error

src/app/main.tsx, src/shared/test/setupMocks.ts
.env 파일에 `VITE_USE_MOCK` 변수를 둬서 값이 true면 MSW를 실행하고
false면 로컬 백엔드 서버를 실행할 수 있도록 분리했습니다.
```ts
export async function setupMocks(): Promise<void> {
if (import.meta.env.MODE !== 'development') {
return;
}
if (import.meta.env.VITE_USE_MOCK !== 'true') return;
const { worker } = await import('../test/browser');
await worker.start({
onUnhandledRequest: (req) => {
const url = new URL(req.url);
if (url.pathname.endsWith('.svg')) {
return; // .svg 파일 요청을 무시
}
},
});
}
```
석원님도 .env 파일 설정하셔서 사용하면 될 듯 합니다.
```.env
// .env 파일
VITE_USE_MOCK=true
```
closes #이슈번호
=> Feat: setupMocks 함수 분리 및 로컬 백엔드와 분리

src/features/register/lib/useDragAndDrop.ts, src/features/register/ui/ImageUploaderInput.tsx
- 드래그가 발생하는 영역에 CSS로 `touch-action: none`을 지정해, 브라우저가 스크롤·핀치 줌 등을 먼저 처리하지 못하도록 막는다.
- pointer events를 지원하지 않는 브라우저를 대비하기 위해 터치 이벤트와 마우스 이벤트 추가.
closes #이슈번호
=> Fix: drag and drop

.github/workflows/integration-main.yml, src/app/main.tsx, src/features/details/ui/AuctionDetailsMain.tsx, src/features/details/ui/PreAuctionDetailsMain.tsx, src/shared/ui/ProgressiveImage.tsx, src/stories/components/product/ProductItem.test.tsx
LCP 매트릭은 사용자가 페이지로 처음 이동한 시점을 기준으로 뷰포트 내에 있는 가장 큰 이미지 또는 텍스트 블록의 렌더링 시간을 측정한다. 
페이지 로드와 LCP 사이에서는 HTTP 연결, 리다이렉트, TTFB, First Paint, FCP 등 많은 일이 일어난다.
우수한 사용자 환경을 제공하려면 사이트에서 페이지 방문의 75% 이상에 대해 LCP가 2.5초 이하가 되도록 노력해야 한다.
- TTFB(Time To First Byte, TTFB): 서버로부터 HTML 문서 로드를 시작하는 데 걸리는 시간 => 보통 CDN 사용해서 TTFB 개선한다.
- 리소스 로드 지연(Resource Load Delay): 브라우저가 LCP 이미지를 탐색하는 데 걸리는 시간.
- 리소스 로드 시간(Resource Load Time): 브라우저가 LCP 이미지를 다운로드하는 데 걸리는 시간.
- 렌더링 지연(Render Delay): 브라우저가 LCP 이미지 또는 기타 LCP 요소를 표시하는 데 걸리는 시간.
이미지 최적화(압축 및 포멧 그리고 워커 사용한 병렬 처리) 이후 3.2초까지 줄였으나, 11초를 넘어가는 문제 발생.
원인은 이미지 로드 속도가 느려 흰 화면이 보이는 문제 발생하여 이를 해결하는 과정에서 발생.
처음에는 고해상도 이미지를 불러오는 과정에서 저해상도 이미지를 빨리 불러와 blur와 opacity 효과주어 사용자가 흰 화면을 보는 시간을 줄이고자 했다. 
하지만 이러한 방식은 브라우저가 LCP 대상으로 어떤 이미지를 선택할지가 불명확해진다. 
처음에 로딩되는 저해상도 이미지(lowResSrc)를 …
=> fix: LCP 지수 개선

.github/workflows/deploy.yml
Vite는 빌드 시 파일 이름에 해시를 추가하여 파일 내용이 변경되지 않으면 동일한 이름을 유지한다.  예를 들어, Pretendard-Medium.woff2 파일은 빌드 후 Pretendard-Medium-Dq5e4H0E.woff2로 변경된다. 이로 인해 브라우저는 이미 다운로드한 파일을 재사용할 수 있다.
브라우저는 기본적으로 캐시 기능을 제공하지만 서버나 CDN에서 HTTP 캐싱 헤더를 명시적으로 설정해야 브라우저가 언제까지 캐시를 유지할지 정확하게 알 수 있다.
즉 Vite의 해시 기반 파일 네이밍과 HTTP 캐싱 헤더 설정이 함께 작동하면 브라우저는 불필요한 네트워크 요청 없이 안정적으로 파일을 캐시할 수 있다.
폰트 파일, favicon, robots.txt, React 관련 라이브러리 등 변경 가능성이 낮은 파일은 배포 시 S3의 캐시 설정을 통해 장기간 캐시함으로써 불필요한 네트워크 요청을 줄여 로딩 시간을 줄일 수 있다.
closes #이슈번호
=> feat: deploy cache 전략 추가

.github/workflows/deploy.yml, .github/workflows/rollback.yml
기존 배포 파일을 previous_build 폴더로 백업한 뒤, 새로운 빌드를 업로드.
배포 오류 발생 시, previous_build 폴더 내용을 다시 메인 디렉토리로 복구한 뒤 CloudFront 캐시를 무효화하는 작업을 수동 실행 가능.
closes #이슈번호
=> feat: rollback workflow 작성

src/app/App.tsx
- window.innerHeight : 브라우저가 이론적 뷰포트로 계산한 값. 모바일 환경에서 주소창이 나타났다/숨겨져도 바로 그 변화를 제대로 반영하지 못하거나, 또는 전체 뷰포트 높이를 그대로 반환해 레이아웃이 의도와 다르게 튀는 상황이 생길 수 있음.
- window.visualViewport.height : 실제 사용자에게 보이는 영역(브라우저 UI가 차지하는 부분 제외)의 높이. 모바일에서 주소창·탭 바가 가려진 영역은 제외되므로, 현재 실시간으로 보이는 뷰포트 정보를 얻을 수 있음.
closes #이슈번호
=> fix: innerHeight를 visualViewport로 변경
